#!/bin/bash

#Kill only namespace docker container and remove containers
docker ps --format {{.Names}} | xargs docker kill >/dev/null
docker ps -a --format {{.Names}} | awk '{print $0}' | xargs docker rm
service docker restart
