#!/bin/bash

#Kill only namespace docker container and remove containers
docker ps | grep obis | xargs docker kill 
docker ps -a | grep obis | awk '{print $1}' | xargs docker rm 
service docker restart
