#!/bin/bash

# Pull in configuration items
source /opt/obis/config/config.sh

#Docker worker host
host_ip="example.oscer.ou.edu"
#If docker is going to ssh to docker host. Need to setup keys and docker_username.
docker_username="mstacy"

#Mongo Data Node
echo "************** Mongo Data Node ***********"
docker volume create --name obis_mongodata
if [ -f /opt/obis/config/thisisfirstrun ]; then
  echo "*********** Create Mongo User ************"
  docker run -it --rm \
    -v obis_mongodata:/data/db:z \
    -v /opt/obis/config/config.sh:/config.sh \
    -v /opt/obis/config/addmongouser:/addmongouser \
    --entrypoint /addmongouser mongo
  rm -f /opt/obis/config/thisisfirstrun
fi

docker run -d --name obis_mongo \
  -v obis_mongodata:/data/db:z \
  -v /opt/obis/config/ssl/backend:/ssl:z \
  mongo --sslMode requireSSL \
        --sslPEMKeyFile /ssl/server/mongodb.pem \
        --sslCAFile /ssl/testca/cacert.pem \
        --auth

#Rabbitmq
echo "************** Rabbitmq        ***********"
docker run -d --name obis_rabbitmq \
  -v /opt/obis/config/ssl/backend:/ssl:z \
  -e "RABBITMQ_DEFAULT_USER=${broker_username}" \
  -e "RABBITMQ_DEFAULT_PASS=${broker_password}" \
  -e "RABBITMQ_DEFAULT_VHOST=${vhost}" \
  -e "RABBITMQ_SSL_CERT_FILE=/ssl/server/cert.pem" \
  -e "RABBITMQ_SSL_KEY_FILE=/ssl/server/key.pem" \
  -e "RABBITMQ_SSL_CA_FILE=/ssl/testca/cacert.pem" \
  rabbitmq #cybercom/rabbitmq

#Celery
echo "********** Celery Async Queue ************"
#-v path_to_key/.ssh:/root/.ssh:z
docker run -d --name obis_celery \
  --link obis_rabbitmq:cybercom_rabbitmq \
  --link obis_mongo:cybercom_mongo \
  -v /opt/obis/config/celery/code:/code:z \
  -v /opt/obis/log:/log:z \
  -v /opt/obis/data:/data:z \
  -v /opt/obis/config/ssl/backend:/ssl:z \
  -e "docker_worker=$host_ip" \
  -e "docker_username=$docker_username" \
  -e "C_FORCE_ROOT=true" \
  -e "CELERY_CONCURRENCY=8" \
  cybercom/celery

#memcache
echo "********* memcached   ********************"
docker run --name obis_memcache -d memcached

#API
echo "*********  API       *********************"
docker run -d --name obis_api \
  -p 8080:8080 \
  -v /opt/obis/config/ssl/backend:/ssl:z \
  -v /opt/obis/api_code:/usr/src/app:z \
  -v /opt/obis/config/api_config.py:/usr/src/app/api/config.py:z \
  -v /opt/obis/log:/log:z \
  -v /opt/obis/data:/data:z \
  obis_api_test

# --link obis_memcache:cybercom_memcache \
#  --link obis_mongo:cybercom_mongo \
#  --link obis_rabbitmq:cybercom_rabbitmq \

# -v /opt/obis/config/db.sqlite3:/usr/src/app/db.sqlite3:z \

# Nginx - if only one platform on system can leave in setup. 
# If multiple cybercommons application running on same system. Comment out and add service with nginx to match api reverse proxy ports from api. See nginx config an default!

echo "********* Nginx        ********************"
docker run -p 81:81 --name obis_nginx \
  --link obis_api \
  -v /opt/obis/data:/data:z \
  -v /opt/obis/config/nginx/nginx.conf:/etc/nginx/nginx.conf:z \
  -v /opt/obis/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:z \
  -d nginx


#Configure and add-ons to containers
#echo "******** Configure Cybercom **************"

#echo "********* Celery Requires wget ************"
#docker exec -it obis_celery apt-get install wget
