#!/bin/bash

# Pull in configuration items
source /opt/obis/config/config.sh

# Docker worker host
# host_ip = "example.oscer.ou.edu"
# If docker is going to ssh to docker host. Need to setup keys and docker_username.
# docker_username = "mstacy"

# OBIS API
echo "************* OBIS API *************"
docker run -d --name obis_api \
  -p 8080:8080 \
  -v /opt/obis/config/ssl/backend:/ssl:z \
  -v /opt/obis/api_code:/usr/src/app:z \
  -v /opt/obis/log:/log:z \
  obis_api

# OBIS NGINX
echo "************ OBIS NGINX ************"
docker run -p 81:81 --name obis_nginx \
  --link obis_api \
  -v /opt/obis/api_code/static:/data/static/:z \
  -v /opt/obis/obis/:/var/www/obis/:z \
  -v /opt/obis/obis_db_scripts/:/var/www/obis_db_scripts/:z \
  -v /opt/obis/api_code/nginx_config/nginx.conf:/etc/nginx/nginx.conf:z \
  -v /opt/obis/api_code/nginx_config/default.conf:/etc/nginx/conf.d/default.conf:z \
  -d nginx
